### ISSUE TITLE
Derivation of the streamlines in Moving Charge

### ISSUE THREAD

**Issue by eugeneybsong** [nv-hiep/Moving_Charge#1]
Dear Mr. Hiep
Your program "Moving-Charge" is a great help for me, which is short and powerful.
I don't have an issue but a request.
Would you share the mathematical derivation of the streamlines of an accelerated moving charge that you used in your program?
I would like to use it for more general radiations.
Thank you so much for your contribution.
Eugene Song

    def cal_lambda(self, t):
        v = self.get_vel(t, self.sel.get())
        gamma = 1. / np.sqrt(1. - v[0][0] ** 2)
        vnorm = self.norm(v)
        vec_n = np.array([np.cos(self.phi), np.sin(self.phi)]).T

        a = vec_n + (gamma - 1.) * np.dot(vec_n, vnorm.T) * vnorm + gamma * v
        b = gamma * (np.dot(v, vec_n.T) + 1.)[0]

        for i in range(len(self.phi)):
            a[i, :] = a[i, :] / b[i]
.            ..............
            x = self.get_pos(xt, stype) + (t - xt) * self.cal_lambda(xt)

**Comment by nv-hiep** [comment]
Hi Eugene,

Here is the original paper. Please take a look. https://www.joerg-enderlein.de/relativistic-charge

Hope this helps.

Cheers,
Hiep

**Comment by eugeneybsong** [comment]
It is great.
Thank you so much for your help.
Blessings
Eugene Song
